/*==================================================================
	
	-----------------------
	-*- [Hide and Seek] -*-
	-----------------------
	
	Filename: hns.inc
	Author: Karsei
	Description: Main header
	
	URL 1: http://karsei.pe.kr
	
	Copyright 2012-2015 by Karsei All Right Reserved
	
==================================================================*/

// Plugin Version
#define HNS_VERSION			"0.8"

// Authors to Plugin Information
#define HNS_CREATOR			"Karsei"
#define HNS_CREATOR_URL		"http://karsei.pe.kr"

// Text Prefix
#define HNS_SERVER_PREFIX	"[HNS]"
#define HNS_CHAT_PREFIX		"[HNS]"

// Definition of client preference
#define HNS_CLIENT_HIDER	1
#define HNS_CLIENT_SEEKER	2




// Headers
#include "hns/hns_client_validation.inc"
#include "hns/hns_stocks.inc"
#include "hns/hns_timer_stocks.inc"
#include "hns/hns_phrases.inc"
#include "hns/hns_admin.inc"
#include "hns/hns_weapon.inc"
#include "hns/hns_core.inc"
#include "hns/hns_option_skill.inc"
